package alphabet

func init() {
	Register(&Alphabet{
		Name:        "german",
		DisplayName: "German",
		Description: "German spelling alphabet (traditional)",
		Letters: map[rune]string{
			'A': "Anton",
			'B': "Berta",
			'C': "Cäsar",
			'D': "Dora",
			'E': "Emil",
			'F': "Friedrich",
			'G': "Gustav",
			'H': "Heinrich",
			'I': "Ida",
			'J': "Julius",
			'K': "Kaufmann",
			'L': "Ludwig",
			'M': "Martha",
			'N': "Nordpol",
			'O': "Otto",
			'P': "Paula",
			'Q': "Quelle",
			'R': "Richard",
			'S': "Samuel",
			'T': "Theodor",
			'U': "Ulrich",
			'V': "Viktor",
			'W': "Wilhelm",
			'X': "Xanthippe",
			'Y': "Ypsilon",
			'Z': "Zacharias",
			// German special characters
			'Ä': "Ärger",
			'Ö': "Ökonom",
			'Ü': "Übermut",
		},
		Digits: map[rune]string{
			'0': "Null",
			'1': "Eins",
			'2': "Zwei",
			'3': "Drei",
			'4': "Vier",
			'5': "Fünf",
			'6': "Sechs",
			'7': "Sieben",
			'8': "Acht",
			'9': "Neun",
		},
	})
}
