package alphabet

func init() {
	Register(&Alphabet{
		Name:        "lapd",
		DisplayName: "LAPD/APCO",
		Description: "US law enforcement phonetic alphabet",
		Letters: map[rune]string{
			'A': "Adam",
			'B': "Boy",
			'C': "Charles",
			'D': "David",
			'E': "Edward",
			'F': "Frank",
			'G': "George",
			'H': "Henry",
			'I': "Ida",
			'J': "John",
			'K': "King",
			'L': "Lincoln",
			'M': "Mary",
			'N': "Nora",
			'O': "Ocean",
			'P': "Paul",
			'Q': "Queen",
			'R': "Robert",
			'S': "Sam",
			'T': "Tom",
			'U': "Union",
			'V': "Victor",
			'W': "William",
			'X': "X-ray",
			'Y': "Young",
			'Z': "Zebra",
		},
		Digits: map[rune]string{
			'0': "Zero",
			'1': "One",
			'2': "Two",
			'3': "Three",
			'4': "Four",
			'5': "Five",
			'6': "Six",
			'7': "Seven",
			'8': "Eight",
			'9': "Niner",
		},
	})
}
