package alphabet

func init() {
	Register(&Alphabet{
		Name:        "western-union",
		DisplayName: "Western Union",
		Description: "Telegraphy phonetic alphabet",
		Letters: map[rune]string{
			'A': "Adams",
			'B': "Boston",
			'C': "Chicago",
			'D': "Denver",
			'E': "Easy",
			'F': "Frank",
			'G': "George",
			'H': "Henry",
			'I': "Ida",
			'J': "John",
			'K': "King",
			'L': "Lincoln",
			'M': "Mary",
			'N': "New York",
			'O': "Ocean",
			'P': "Peter",
			'Q': "Queen",
			'R': "Roger",
			'S': "Sugar",
			'T': "Thomas",
			'U': "Union",
			'V': "Victor",
			'W': "William",
			'X': "X-ray",
			'Y': "Young",
			'Z': "Zero",
		},
		Digits: map[rune]string{
			'0': "Zero",
			'1': "One",
			'2': "Two",
			'3': "Three",
			'4': "Four",
			'5': "Five",
			'6': "Six",
			'7': "Seven",
			'8': "Eight",
			'9': "Niner",
		},
	})
}
